name: ci

on:
  workflow_call:
  pull_request:
    branches:
      - "**"
env:
  TZ: Asia/Tokyo

jobs:
  pre-testing:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CARGO_INCREMENTAL: 0
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.87.0
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cargo-cache"
      #   - name: Install cargo-nextest
      #     uses: baptiste0928/cargo-install@v2
      #     with:
      #       crate: cargo-nextest
      - name: Install cargo-nextest
        run: cargo install cargo-nextest --version 0.9.98 --locked
      - name: build
        run: |
          cargo nextest run --no-run
